# -*- coding: utf-8 -*-
"""PredictCovid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/193ehDmaCMTSiB7iLL5AVZLB2FM5h38Il

This package allows me to use pytrends to get current data directly from Google Trends.
"""

pip install pytrends

"""Importing all relevant libraries and tools."""

from pytrends.request import TrendReq
import pandas as pd
import numpy as np
import statsmodels.api as sm
from datetime import datetime
from sklearn import linear_model
import matplotlib.pyplot as plt

"""Initiating Pytrends."""

pytrends = TrendReq(hl='en-US', tz=360)

"""Creating a list with predictor variables for the ols model."""

kw_list = ["cough","fever","headache","diarrhea","covid symptoms"]
pytrends.build_payload(kw_list, cat=0, timeframe='2020-01-26 2021-01-03', geo='US')

"""Creating a DataFrame object for predictor variables."""

df = pytrends.interest_over_time()
df.columns = ["cough","fever","headache","diarrhea","covid symptoms","value"]
del df['value']
print(df)

"""Importing CDC daily new infection numbers."""

cdc_daily = pd.read_csv("/content/case_daily_trends__united_states.csv")
print(cdc_daily)

"""Convert daily data into weekly data."""

cdc_daily['Date'] = cdc_daily['Date'].astype('datetime64[ns]')
cdc_weekly = cdc_daily.resample('W-Sun', label='right', closed = 'right', on='Date').sum().reset_index().sort_values(by='Date')
print(cdc_weekly)

"""

Defining plot variables"""

a = df[["covid symptoms"]].values.tolist()
b = cdc_weekly["New Cases"].values.tolist()

"""Plot Variables to identify trends"""

colors = '#9c0c2e'
area = np.pi*8

plt.scatter(a, b, s=area, c=colors, alpha=0.5)
plt.title('Scatter Plot Symptom Searches - New Cases')
plt.show()

"""Defining OLS Variables"""

x = df[["cough","fever","headache","diarrhea","covid symptoms"]].values.tolist()
y = cdc_weekly["New Cases"].values.tolist()

"""Adding the constant term and running the regression and fitting the model."""

x = sm.add_constant(x)
result = sm.OLS(y, x).fit() 
print(result.summary())

"""Predict Covid Cases"""

kw_list = ["cough","fever","headache","diarrhea","covid symptoms"]
pytrends.build_payload(kw_list, cat=0, timeframe='2021-01-03 2021-01-09', geo='US')
df2 = pytrends.interest_over_time()
df2.columns = ["cough","fever","headache","diarrhea","covid symptoms","value"]
del df2['value']
print(df2)

predict_x = [1,27,42,34,29,74]
weekly_positives = result.predict(predict_x)
daily_positives = weekly_positives / 7
print(daily_positives)